<?php
/* 
twtAgent.php - logs who reads your twtxt.txt

Based on: https://gist.mills.io/prologic/223ef70ac7334b48acafcc095a7a9262 (generated by ChatGPT, 2024-09-28)

To get twtAgent.php to work you need to add this to your .htaccess file:

RewriteEngine on
Redirect /twtAgent.php /twtxt.txt 
RewriteRule /twtxt.txt /twtAgent.php

---

# TODO:

- [x] Implement support for 'If-Modified-Since' header

- [ ] Look into parsing the log: https://git.mills.io/yarnsocial/useragent

- [ ] Limit the size of the log file
    - Only save the latest requests from each user agent
    - Only keep log for one week

- [ ] Implement this in timeline in some way
    - Move into it one folder: /twtAgents/
    - Integrate it into the UI under: /followers

- [ ] Find a better name
    - twtLog
    - twtUserAgents
    - twtFollowers    
*/


// Path to the text file to be served
$twtFile = 'twtxt.txt';

// Path to the log file where User-Agents will be saved
$logFile = 'twtAgent.log';

// 2024-12-01 @eapl - Moved the file_exists check before
// to avoid having an if-else. The code will stop on the exit.

// If the file doesn't exist, return a 404 response
if (!file_exists($twtFile)) {
    // 2024-12-01 @eapl - Changed this header to the response code 404
    // I think it's cleaner
    //header("HTTP/1.1 404 Not Found");

    http_response_code(404);
    echo "File not found.";
    exit;
}

// Parse the HTTP request headers to get the User-Agent
if (isset($_SERVER['HTTP_USER_AGENT'])) {
    $timestamp = str_replace("+00:00", "Z", date(DATE_RFC3339));
    $userAgent = $_SERVER['HTTP_USER_AGENT'];

    // Open the log file for appending and write the User-Agent
    file_put_contents($logFile, $timestamp . "\t" . $userAgent . PHP_EOL, FILE_APPEND | LOCK_EX);
}

// Serve the twtxt.txt file

// Get the last modified time of the file
$lastModifiedTime = filemtime($twtFile);
$lastModified = gmdate('D, d M Y H:i:s', $lastModifiedTime) . ' GMT';

// Check for the If-Modified-Since header
if (isset($_SERVER['HTTP_IF_MODIFIED_SINCE'])) {
    $ifModifiedSince = strtotime($_SERVER['HTTP_IF_MODIFIED_SINCE']);

    // Compare the file's last modification time with the header
    if ($ifModifiedSince >= $lastModifiedTime) {
        http_response_code(304); // Not Modified
        exit;
    }
}

header('Content-Type: text/plain');
header('Content-Disposition: inline; filename="' . basename($twtFile) . '"');
header('Content-Length: ' . filesize($twtFile));
header("Last-Modified: $lastModified");

// Output the content
readfile($twtFile);
