<?php

/* 

twtAgent.php - log who reads your twtxt.txt

Based on: https://gist.mills.io/prologic/223ef70ac7334b48acafcc095a7a9262 (generated by ChatGPT, 2024-09-28)

To get twtAgent.php to work you need to add this to your .htaccess file:

RewriteEngine on
Redirect /twtxt.txt /twtAgent.php

---

# TODO:
    
- [ ] Look into parsing the log: https://git.mills.io/yarnsocial/useragent

- [ ] Limit the size of the log file
    - Only save the latest requests from each user agent
    - Only keep log for one week

- [ ] Implement this in timeline in some way
    - Move into it one folder: /twtAgents/
    - Integrate it into the UI under: /followers

- Find a better name
    - twtLog
    - twtUserAgents
    - twtFollowers    
*/

// Path to the text file to be served
$twtFile = 'twtxt.txt';

// Path to the log file where User-Agents will be saved
$logFile = 'twtAgent.log';

// Serve the text file content
if (file_exists($twtFile)) {

    // Set appropriate headers to serve a plain text file
    header('Content-Type: text/plain');
    header('Content-Disposition: inline; filename="' . basename($twtFile) . '"');
    header('Content-Length: ' . filesize($twtFile));
    
    // Output the text file
    readfile($twtFile);

} else {

    // If the file doesn't exist, return a 404 response
    header("HTTP/1.0 404 Not Found");
    echo "File not found.";
    exit;
}

// Parse the HTTP request headers to get the User-Agent
if (isset($_SERVER['HTTP_USER_AGENT'])) {
    $timestamp = str_replace("+00:00","Z",date(DATE_RFC3339));
    $userAgent = $_SERVER['HTTP_USER_AGENT'];

    // Open the log file for appending and write the User-Agent
    file_put_contents($logFile, $timestamp . "\t" . $userAgent . PHP_EOL, FILE_APPEND | LOCK_EX);
}